# animation-1
domain_lora_scale: 1.0
adapter_lora_path: "models/Motion_Module/v3_sd15_adapter.ckpt"
dreambooth_path:   "models/DreamBooth_LoRA/Counterfeit.safetensors"

inference_config: "configs/inference/inference-v3.yaml"
motion_module:    "models/Motion_Module/v3_sd15_mm.ckpt"

controlnet_config: "configs/inference/sparsectrl/latent_condition.yaml"
controlnet_path:   "models/SparseCtrl/v3_sd15_sparsectrl_rgb.ckpt"